-- Give the existing service primary key the explicit name used by the API.
-- PostgreSQL updates dependent foreign keys automatically when a column is renamed.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = current_schema() AND table_name = 'service_types' AND column_name = 'id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                       WHERE table_schema = current_schema() AND table_name = 'service_types' AND column_name = 'service_id') THEN
        ALTER TABLE service_types RENAME COLUMN id TO service_id;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS bike_companies (
    bike_company_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(120) NOT NULL UNIQUE,
    company_short_name VARCHAR(50) NOT NULL UNIQUE,
    company_long_name VARCHAR(180) NOT NULL,
    company_description TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bike_companies_short_name_check CHECK (company_short_name ~ '^[A-Z0-9_]+$')
);

CREATE TABLE IF NOT EXISTS bike_models (
    bike_model_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bike_company_id INTEGER NOT NULL REFERENCES bike_companies(bike_company_id),
    model_name VARCHAR(120) NOT NULL,
    model_short_name VARCHAR(60) NOT NULL,
    model_long_name VARCHAR(180) NOT NULL,
    model_description TEXT,
    engine_cc NUMERIC(7,2),
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bike_models_company_short_name_key UNIQUE (bike_company_id, model_short_name),
    CONSTRAINT bike_models_id_company_key UNIQUE (bike_model_id, bike_company_id),
    CONSTRAINT bike_models_short_name_check CHECK (model_short_name ~ '^[A-Z0-9_]+$'),
    CONSTRAINT bike_models_engine_cc_check CHECK (engine_cc IS NULL OR engine_cc > 0)
);

CREATE INDEX IF NOT EXISTS bike_models_company_id_idx ON bike_models (bike_company_id);

CREATE TABLE IF NOT EXISTS car_companies (
    car_company_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(120) NOT NULL UNIQUE,
    company_short_name VARCHAR(50) NOT NULL UNIQUE,
    company_long_name VARCHAR(180) NOT NULL,
    company_description TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT car_companies_short_name_check CHECK (company_short_name ~ '^[A-Z0-9_]+$')
);

CREATE TABLE IF NOT EXISTS car_models (
    car_model_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_company_id INTEGER NOT NULL REFERENCES car_companies(car_company_id),
    model_name VARCHAR(120) NOT NULL,
    model_short_name VARCHAR(60) NOT NULL,
    model_long_name VARCHAR(180) NOT NULL,
    model_description TEXT,
    engine_cc NUMERIC(7,2),
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT car_models_company_short_name_key UNIQUE (car_company_id, model_short_name),
    CONSTRAINT car_models_id_company_key UNIQUE (car_model_id, car_company_id),
    CONSTRAINT car_models_short_name_check CHECK (model_short_name ~ '^[A-Z0-9_]+$'),
    CONSTRAINT car_models_engine_cc_check CHECK (engine_cc IS NULL OR engine_cc > 0)
);

CREATE INDEX IF NOT EXISTS car_models_company_id_idx ON car_models (car_company_id);

-- A service centre first selects a service, then the makes and models it supports.
CREATE TABLE IF NOT EXISTS service_center_bike_companies (
    service_center_id BIGINT NOT NULL REFERENCES service_centers(service_center_id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES service_types(service_id),
    bike_company_id INTEGER NOT NULL REFERENCES bike_companies(bike_company_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (service_center_id, service_id, bike_company_id),
    FOREIGN KEY (service_center_id, service_id)
        REFERENCES service_center_services(service_center_id, service_type_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS service_center_bike_models (
    service_center_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    bike_company_id INTEGER NOT NULL,
    bike_model_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (service_center_id, service_id, bike_model_id),
    FOREIGN KEY (service_center_id, service_id, bike_company_id)
        REFERENCES service_center_bike_companies(service_center_id, service_id, bike_company_id)
        ON DELETE CASCADE,
    FOREIGN KEY (bike_model_id, bike_company_id)
        REFERENCES bike_models(bike_model_id, bike_company_id)
);

CREATE TABLE IF NOT EXISTS service_center_car_companies (
    service_center_id BIGINT NOT NULL REFERENCES service_centers(service_center_id) ON DELETE CASCADE,
    service_id BIGINT NOT NULL REFERENCES service_types(service_id),
    car_company_id INTEGER NOT NULL REFERENCES car_companies(car_company_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (service_center_id, service_id, car_company_id),
    FOREIGN KEY (service_center_id, service_id)
        REFERENCES service_center_services(service_center_id, service_type_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS service_center_car_models (
    service_center_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    car_company_id INTEGER NOT NULL,
    car_model_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (service_center_id, service_id, car_model_id),
    FOREIGN KEY (service_center_id, service_id, car_company_id)
        REFERENCES service_center_car_companies(service_center_id, service_id, car_company_id)
        ON DELETE CASCADE,
    FOREIGN KEY (car_model_id, car_company_id)
        REFERENCES car_models(car_model_id, car_company_id)
);

INSERT INTO bike_companies
    (company_name, company_short_name, company_long_name, company_description)
VALUES
    ('Hero', 'HERO', 'Hero MotoCorp Limited', 'Indian motorcycle and scooter manufacturer'),
    ('Honda', 'HONDA', 'Honda Motorcycle and Scooter India', 'Motorcycle and scooter manufacturer in India'),
    ('TVS', 'TVS', 'TVS Motor Company Limited', 'Indian motorcycle and scooter manufacturer'),
    ('Bajaj', 'BAJAJ', 'Bajaj Auto Limited', 'Indian motorcycle manufacturer'),
    ('Royal Enfield', 'ROYAL_ENFIELD', 'Royal Enfield', 'Indian mid-size motorcycle brand'),
    ('Yamaha', 'YAMAHA', 'India Yamaha Motor', 'Motorcycle and scooter manufacturer in India'),
    ('Suzuki', 'SUZUKI', 'Suzuki Motorcycle India', 'Motorcycle and scooter manufacturer in India'),
    ('KTM', 'KTM', 'KTM India', 'Performance motorcycle brand in India'),
    ('Jawa Yezdi', 'JAWA_YEZDI', 'Jawa Yezdi Motorcycles', 'Classic Legends motorcycle brands in India'),
    ('Ather', 'ATHER', 'Ather Energy Limited', 'Indian electric scooter manufacturer'),
    ('Ola Electric', 'OLA_ELECTRIC', 'Ola Electric Mobility Limited', 'Indian electric two-wheeler manufacturer')
ON CONFLICT (company_short_name) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    company_long_name = EXCLUDED.company_long_name,
    company_description = EXCLUDED.company_description;

WITH seed(company_code, model_name, model_code, engine_cc) AS (VALUES
    ('HERO','Splendor Plus','SPLENDOR_PLUS',97.20), ('HERO','HF Deluxe','HF_DELUXE',97.20),
    ('HERO','Glamour','GLAMOUR',124.70), ('HERO','Xtreme 125R','XTREME_125R',124.70),
    ('HERO','Xpulse 200 4V','XPULSE_200_4V',199.60),
    ('HONDA','Activa','ACTIVA',109.51), ('HONDA','Dio','DIO',109.51),
    ('HONDA','Shine 125','SHINE_125',123.94), ('HONDA','SP125','SP125',123.94),
    ('HONDA','Unicorn','UNICORN',162.71), ('HONDA','Hornet 2.0','HORNET_2_0',184.40),
    ('TVS','Jupiter','JUPITER',113.30), ('TVS','Ntorq 125','NTORQ_125',124.80),
    ('TVS','Raider 125','RAIDER_125',124.80), ('TVS','Apache RTR 160','APACHE_RTR_160',159.70),
    ('TVS','Apache RTR 200 4V','APACHE_RTR_200_4V',197.75), ('TVS','Ronin','RONIN',225.90),
    ('BAJAJ','Pulsar N160','PULSAR_N160',164.82), ('BAJAJ','Pulsar NS200','PULSAR_NS200',199.50),
    ('BAJAJ','Pulsar 220F','PULSAR_220F',220.00), ('BAJAJ','Platina 100','PLATINA_100',102.00),
    ('BAJAJ','Avenger Street 160','AVENGER_STREET_160',160.00), ('BAJAJ','Dominar 400','DOMINAR_400',373.30),
    ('ROYAL_ENFIELD','Classic 350','CLASSIC_350',349.00), ('ROYAL_ENFIELD','Bullet 350','BULLET_350',349.00),
    ('ROYAL_ENFIELD','Hunter 350','HUNTER_350',349.00), ('ROYAL_ENFIELD','Meteor 350','METEOR_350',349.00),
    ('ROYAL_ENFIELD','Himalayan 450','HIMALAYAN_450',452.00), ('ROYAL_ENFIELD','Interceptor 650','INTERCEPTOR_650',648.00),
    ('YAMAHA','R15 V4','R15_V4',155.00), ('YAMAHA','MT-15 V2','MT_15_V2',155.00),
    ('YAMAHA','FZ-S FI','FZ_S_FI',149.00), ('YAMAHA','Fascino 125','FASCINO_125',125.00),
    ('YAMAHA','Aerox 155','AEROX_155',155.00),
    ('SUZUKI','Access 125','ACCESS_125',124.00), ('SUZUKI','Burgman Street','BURGMAN_STREET',124.00),
    ('SUZUKI','Gixxer','GIXXER',155.00), ('SUZUKI','V-Strom SX','V_STROM_SX',249.00),
    ('KTM','200 Duke','DUKE_200',199.50), ('KTM','250 Duke','DUKE_250',249.07),
    ('KTM','390 Duke','DUKE_390',398.63), ('KTM','RC 390','RC_390',373.27),
    ('JAWA_YEZDI','Jawa 350','JAWA_350',334.00), ('JAWA_YEZDI','Jawa 42','JAWA_42',294.72),
    ('JAWA_YEZDI','Yezdi Roadster','YEZDI_ROADSTER',334.00), ('JAWA_YEZDI','Yezdi Adventure','YEZDI_ADVENTURE',334.00),
    ('ATHER','450X','450X',NULL), ('ATHER','Rizta','RIZTA',NULL),
    ('OLA_ELECTRIC','S1 Pro','S1_PRO',NULL), ('OLA_ELECTRIC','S1 X','S1_X',NULL)
)
INSERT INTO bike_models
    (bike_company_id, model_name, model_short_name, model_long_name, model_description, engine_cc)
SELECT company.bike_company_id, seed.model_name, seed.model_code,
       company.company_name || ' ' || seed.model_name,
       seed.model_name || ' model by ' || company.company_name, seed.engine_cc
FROM seed JOIN bike_companies company ON company.company_short_name = seed.company_code
ON CONFLICT (bike_company_id, model_short_name) DO UPDATE SET
    model_name = EXCLUDED.model_name, model_long_name = EXCLUDED.model_long_name,
    model_description = EXCLUDED.model_description, engine_cc = EXCLUDED.engine_cc;

INSERT INTO car_companies
    (company_name, company_short_name, company_long_name, company_description)
VALUES
    ('Maruti Suzuki', 'MARUTI_SUZUKI', 'Maruti Suzuki India Limited', 'Passenger vehicle manufacturer in India'),
    ('Hyundai', 'HYUNDAI', 'Hyundai Motor India Limited', 'Passenger vehicle manufacturer in India'),
    ('Tata Motors', 'TATA', 'Tata Motors Passenger Vehicles Limited', 'Indian passenger and electric vehicle manufacturer'),
    ('Mahindra', 'MAHINDRA', 'Mahindra & Mahindra Limited', 'Indian SUV and utility vehicle manufacturer'),
    ('Toyota', 'TOYOTA', 'Toyota Kirloskar Motor', 'Passenger and utility vehicle manufacturer in India'),
    ('Kia', 'KIA', 'Kia India Private Limited', 'Passenger vehicle manufacturer in India'),
    ('Honda', 'HONDA', 'Honda Cars India Limited', 'Passenger vehicle manufacturer in India'),
    ('MG', 'MG', 'JSW MG Motor India', 'Passenger and electric vehicle manufacturer in India'),
    ('Skoda', 'SKODA', 'Skoda Auto Volkswagen India', 'Passenger vehicle manufacturer in India'),
    ('Volkswagen', 'VOLKSWAGEN', 'Volkswagen India', 'Passenger vehicle manufacturer in India'),
    ('Renault', 'RENAULT', 'Renault India', 'Passenger vehicle manufacturer in India'),
    ('Nissan', 'NISSAN', 'Nissan Motor India', 'Passenger vehicle manufacturer in India'),
    ('Jeep', 'JEEP', 'Jeep India', 'SUV manufacturer in India'),
    ('Citroen', 'CITROEN', 'Citroen India', 'Passenger vehicle manufacturer in India'),
    ('BYD', 'BYD', 'BYD India', 'Electric passenger vehicle manufacturer in India')
ON CONFLICT (company_short_name) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    company_long_name = EXCLUDED.company_long_name,
    company_description = EXCLUDED.company_description;

WITH seed(company_code, model_name, model_code, engine_cc) AS (VALUES
    ('MARUTI_SUZUKI','Alto K10','ALTO_K10',998), ('MARUTI_SUZUKI','WagonR','WAGONR',1197),
    ('MARUTI_SUZUKI','Swift','SWIFT',1197), ('MARUTI_SUZUKI','Baleno','BALENO',1197),
    ('MARUTI_SUZUKI','Dzire','DZIRE',1197), ('MARUTI_SUZUKI','Brezza','BREZZA',1462),
    ('MARUTI_SUZUKI','Ertiga','ERTIGA',1462), ('MARUTI_SUZUKI','Fronx','FRONX',1197),
    ('MARUTI_SUZUKI','Grand Vitara','GRAND_VITARA',1462),
    ('HYUNDAI','Grand i10 Nios','GRAND_I10_NIOS',1197), ('HYUNDAI','i20','I20',1197),
    ('HYUNDAI','Aura','AURA',1197), ('HYUNDAI','Exter','EXTER',1197),
    ('HYUNDAI','Venue','VENUE',1197), ('HYUNDAI','Creta','CRETA',1497),
    ('HYUNDAI','Verna','VERNA',1497), ('HYUNDAI','Alcazar','ALCAZAR',1493),
    ('TATA','Tiago','TIAGO',1199), ('TATA','Tigor','TIGOR',1199), ('TATA','Altroz','ALTROZ',1199),
    ('TATA','Punch','PUNCH',1199), ('TATA','Nexon','NEXON',1199), ('TATA','Curvv','CURVV',1199),
    ('TATA','Harrier','HARRIER',1956), ('TATA','Safari','SAFARI',1956),
    ('MAHINDRA','XUV 3XO','XUV_3XO',1197), ('MAHINDRA','Thar','THAR',1997),
    ('MAHINDRA','Scorpio-N','SCORPIO_N',1997), ('MAHINDRA','XUV700','XUV700',1997),
    ('MAHINDRA','Bolero','BOLERO',1493),
    ('TOYOTA','Glanza','GLANZA',1197), ('TOYOTA','Urban Cruiser Taisor','TAISOR',1197),
    ('TOYOTA','Urban Cruiser Hyryder','HYRYDER',1462), ('TOYOTA','Innova Hycross','INNOVA_HYCROSS',1987),
    ('TOYOTA','Fortuner','FORTUNER',2755), ('TOYOTA','Camry','CAMRY',2487),
    ('KIA','Sonet','SONET',1197), ('KIA','Seltos','SELTOS',1497), ('KIA','Carens','CARENS',1497),
    ('KIA','Carnival','CARNIVAL',2151),
    ('HONDA','Amaze','AMAZE',1199), ('HONDA','City','CITY',1498), ('HONDA','Elevate','ELEVATE',1498),
    ('MG','Comet EV','COMET_EV',NULL), ('MG','Windsor EV','WINDSOR_EV',NULL),
    ('MG','Astor','ASTOR',1498), ('MG','Hector','HECTOR',1451), ('MG','Gloster','GLOSTER',1996),
    ('SKODA','Kylaq','KYLAQ',999), ('SKODA','Kushaq','KUSHAQ',999),
    ('SKODA','Slavia','SLAVIA',999), ('SKODA','Kodiaq','KODIAQ',1984),
    ('VOLKSWAGEN','Virtus','VIRTUS',999), ('VOLKSWAGEN','Taigun','TAIGUN',999),
    ('VOLKSWAGEN','Tiguan','TIGUAN',1984),
    ('RENAULT','Kwid','KWID',999), ('RENAULT','Triber','TRIBER',999), ('RENAULT','Kiger','KIGER',999),
    ('NISSAN','Magnite','MAGNITE',999), ('NISSAN','X-Trail','X_TRAIL',1498),
    ('JEEP','Compass','COMPASS',1956), ('JEEP','Meridian','MERIDIAN',1956), ('JEEP','Wrangler','WRANGLER',1995),
    ('CITROEN','C3','C3',1199), ('CITROEN','C3 Aircross','C3_AIRCROSS',1199),
    ('CITROEN','Basalt','BASALT',1199), ('CITROEN','eC3','EC3',NULL),
    ('BYD','Atto 3','ATTO_3',NULL), ('BYD','Seal','SEAL',NULL), ('BYD','eMAX 7','EMAX_7',NULL)
)
INSERT INTO car_models
    (car_company_id, model_name, model_short_name, model_long_name, model_description, engine_cc)
SELECT company.car_company_id, seed.model_name, seed.model_code,
       company.company_name || ' ' || seed.model_name,
       seed.model_name || ' model by ' || company.company_name, seed.engine_cc
FROM seed JOIN car_companies company ON company.company_short_name = seed.company_code
ON CONFLICT (car_company_id, model_short_name) DO UPDATE SET
    model_name = EXCLUDED.model_name, model_long_name = EXCLUDED.model_long_name,
    model_description = EXCLUDED.model_description, engine_cc = EXCLUDED.engine_cc;
