-- Convert the original one-vehicle-per-user table without losing existing data.
ALTER TABLE user_vehicle_details DROP CONSTRAINT IF EXISTS user_vehicle_details_pkey;
ALTER TABLE user_vehicle_details ADD COLUMN IF NOT EXISTS vehicle_id INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE user_vehicle_details ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT FALSE;

-- Each existing record was the user's only vehicle, so it becomes primary.
UPDATE user_vehicle_details SET is_primary = TRUE WHERE is_primary = FALSE;

ALTER TABLE user_vehicle_details ALTER COLUMN vehicle_id SET NOT NULL;
ALTER TABLE user_vehicle_details ADD CONSTRAINT user_vehicle_details_pkey PRIMARY KEY (vehicle_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_vehicle_details_one_primary_per_user_key
    ON user_vehicle_details (user_id) WHERE is_primary = TRUE;
CREATE INDEX IF NOT EXISTS user_vehicle_details_user_id_idx ON user_vehicle_details (user_id, is_primary DESC, vehicle_id);

-- A service type applies to either two-wheelers or four-wheelers. Electric
-- variants use their corresponding base category.
ALTER TABLE service_types ADD COLUMN IF NOT EXISTS vehicle_category VARCHAR(10);
UPDATE service_types
SET vehicle_category = CASE
    WHEN service_code LIKE 'BIKE_%' THEN 'BIKE'
    WHEN service_code LIKE 'CAR_%' THEN 'CAR'
END
WHERE vehicle_category IS NULL;
ALTER TABLE service_types ALTER COLUMN vehicle_category SET NOT NULL;
ALTER TABLE service_types DROP CONSTRAINT IF EXISTS service_types_vehicle_category_check;
ALTER TABLE service_types ADD CONSTRAINT service_types_vehicle_category_check
    CHECK (vehicle_category IN ('BIKE', 'CAR'));

CREATE TABLE IF NOT EXISTS service_sub_types (
    sub_service_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id INTEGER NOT NULL REFERENCES service_types(service_id) ON DELETE CASCADE,
    sub_service_code VARCHAR(60) NOT NULL,
    sub_service_name VARCHAR(120) NOT NULL,
    sub_service_description TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT service_sub_types_service_code_key UNIQUE (service_id, sub_service_code)
);
CREATE INDEX IF NOT EXISTS service_sub_types_service_id_idx
    ON service_sub_types (service_id, is_enabled);

INSERT INTO service_sub_types
    (service_id, sub_service_code, sub_service_name, sub_service_description)
SELECT service.service_id, item.code, item.name, item.description
FROM service_types service
CROSS JOIN (VALUES
    ('WALK_IN', 'Walk In Service', 'Customer brings the vehicle to the service centre'),
    ('PICK_N_DROP', 'PickNDrop', 'Vehicle pickup from and drop-off at the customer location'),
    ('HOME_SERVICE', 'Home Service', 'Technician provides the service at the customer location')
) AS item(code, name, description)
ON CONFLICT (service_id, sub_service_code) DO UPDATE SET
    sub_service_name = EXCLUDED.sub_service_name,
    sub_service_description = EXCLUDED.sub_service_description;
