-- Home-screen visibility and descriptions belong to the top-level service.
ALTER TABLE service_types ADD COLUMN IF NOT EXISTS service_description TEXT;
ALTER TABLE service_types ADD COLUMN IF NOT EXISTS is_home_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE service_types ADD COLUMN IF NOT EXISTS home_display_order INTEGER;

-- Repair and puncture apply to either a bike or a car; existing services
-- retain their BIKE/CAR category.
ALTER TABLE service_types DROP CONSTRAINT IF EXISTS service_types_vehicle_category_check;
ALTER TABLE service_types ADD CONSTRAINT service_types_vehicle_category_check
    CHECK (vehicle_category IN ('BIKE', 'CAR', 'ANY'));

INSERT INTO service_types
    (service_code, service_name, service_type, vehicle_category, service_description, is_home_enabled, home_display_order)
VALUES
    ('RUNNING_REPAIR', 'Running Repair', 'repair', 'ANY', 'Repair for a vehicle that is not running correctly', TRUE, 5),
    ('PUNCTURE', 'Puncture', 'repair', 'ANY', 'Tyre puncture repair service', TRUE, 6)
ON CONFLICT (service_code) DO UPDATE SET
    service_name = EXCLUDED.service_name,
    service_type = EXCLUDED.service_type,
    vehicle_category = EXCLUDED.vehicle_category,
    service_description = EXCLUDED.service_description,
    is_home_enabled = EXCLUDED.is_home_enabled,
    home_display_order = EXCLUDED.home_display_order;

UPDATE service_types SET
    service_description = CASE service_code
        WHEN 'BIKE_SERVICE' THEN 'Regular maintenance and repair for bikes'
        WHEN 'CAR_SERVICE' THEN 'Regular maintenance and repair for cars'
        WHEN 'BIKE_WASHING' THEN 'Professional washing for bikes'
        WHEN 'CAR_WASHING' THEN 'Professional washing for cars'
        ELSE service_description
    END,
    is_home_enabled = TRUE,
    home_display_order = CASE service_code
        WHEN 'BIKE_SERVICE' THEN 1 WHEN 'CAR_SERVICE' THEN 2
        WHEN 'BIKE_WASHING' THEN 3 WHEN 'CAR_WASHING' THEN 4
        WHEN 'RUNNING_REPAIR' THEN 5 WHEN 'PUNCTURE' THEN 6
        ELSE home_display_order
    END
WHERE service_code IN ('BIKE_SERVICE', 'CAR_SERVICE', 'BIKE_WASHING', 'CAR_WASHING', 'RUNNING_REPAIR', 'PUNCTURE');

-- Service options describe the required work. Delivery modes remain in
-- service_sub_types, so either dimension can grow independently.
CREATE TABLE IF NOT EXISTS service_options (
    service_option_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id INTEGER NOT NULL REFERENCES service_types(service_id) ON DELETE CASCADE,
    service_option_code VARCHAR(80) NOT NULL,
    service_option_name VARCHAR(150) NOT NULL,
    service_option_description TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT service_options_service_code_key UNIQUE (service_id, service_option_code)
);
CREATE UNIQUE INDEX IF NOT EXISTS service_options_one_default_per_service_key
    ON service_options (service_id) WHERE is_default = TRUE;
CREATE INDEX IF NOT EXISTS service_options_service_id_idx
    ON service_options (service_id, is_enabled, display_order);

WITH option_seed(service_code, option_code, option_name, option_description, is_default, display_order) AS (VALUES
    ('BIKE_SERVICE', 'GENERAL_SERVICE', 'General Service', 'Standard scheduled bike service', TRUE, 1),
    ('BIKE_SERVICE', 'GENERAL_SERVICE_ENGINE_OIL', 'General Service with Engine Oil', 'Standard bike service including engine oil replacement', FALSE, 2),
    ('BIKE_SERVICE', 'JUMP_START', 'Jump Start', 'Battery jump-start assistance', FALSE, 3),
    ('BIKE_SERVICE', 'RUNNING_REPAIR', 'Running Repair', 'Diagnosis and repair for running issues', FALSE, 4),
    ('BIKE_SERVICE', 'PUNCTURE', 'Puncture', 'Tyre puncture repair', FALSE, 5),
    ('CAR_SERVICE', 'GENERAL_SERVICE', 'General Service', 'Standard scheduled car service', TRUE, 1),
    ('CAR_SERVICE', 'GENERAL_SERVICE_ENGINE_OIL', 'General Service with Engine Oil', 'Standard car service including engine oil replacement', FALSE, 2),
    ('CAR_SERVICE', 'JUMP_START', 'Jump Start', 'Battery jump-start assistance', FALSE, 3),
    ('CAR_SERVICE', 'RUNNING_REPAIR', 'Running Repair', 'Diagnosis and repair for running issues', FALSE, 4),
    ('CAR_SERVICE', 'PUNCTURE', 'Puncture', 'Tyre puncture repair', FALSE, 5),
    ('RUNNING_REPAIR', 'RUNNING_REPAIR', 'Running Repair', 'Diagnosis and repair for running issues', TRUE, 1),
    ('RUNNING_REPAIR', 'GENERAL_SERVICE', 'General Service', 'Standard scheduled service', FALSE, 2),
    ('RUNNING_REPAIR', 'GENERAL_SERVICE_ENGINE_OIL', 'General Service with Engine Oil', 'Service including engine oil replacement', FALSE, 3),
    ('RUNNING_REPAIR', 'JUMP_START', 'Jump Start', 'Battery jump-start assistance', FALSE, 4),
    ('RUNNING_REPAIR', 'PUNCTURE', 'Puncture', 'Tyre puncture repair', FALSE, 5),
    ('PUNCTURE', 'PUNCTURE', 'Puncture', 'Tyre puncture repair', TRUE, 1),
    ('PUNCTURE', 'GENERAL_SERVICE', 'General Service', 'Standard scheduled service', FALSE, 2),
    ('PUNCTURE', 'GENERAL_SERVICE_ENGINE_OIL', 'General Service with Engine Oil', 'Service including engine oil replacement', FALSE, 3),
    ('PUNCTURE', 'JUMP_START', 'Jump Start', 'Battery jump-start assistance', FALSE, 4),
    ('PUNCTURE', 'RUNNING_REPAIR', 'Running Repair', 'Diagnosis and repair for running issues', FALSE, 5)
)
INSERT INTO service_options
    (service_id, service_option_code, service_option_name, service_option_description, is_default, display_order)
SELECT service.service_id, seed.option_code, seed.option_name, seed.option_description, seed.is_default, seed.display_order
FROM option_seed seed JOIN service_types service ON service.service_code = seed.service_code
ON CONFLICT (service_id, service_option_code) DO UPDATE SET
    service_option_name = EXCLUDED.service_option_name,
    service_option_description = EXCLUDED.service_option_description,
    is_default = EXCLUDED.is_default,
    display_order = EXCLUDED.display_order;

-- New featured services receive the same delivery options as other services.
INSERT INTO service_sub_types (service_id, sub_service_code, sub_service_name, sub_service_description)
SELECT service.service_id, item.code, item.name, item.description
FROM service_types service
CROSS JOIN (VALUES
    ('WALK_IN', 'Walk In Service', 'Customer brings the vehicle to the service centre'),
    ('PICK_N_DROP', 'PickNDrop', 'Vehicle pickup from and drop-off at the customer location'),
    ('HOME_SERVICE', 'Home Service', 'Technician provides the service at the customer location')
) AS item(code, name, description)
WHERE service.service_code IN ('RUNNING_REPAIR', 'PUNCTURE')
ON CONFLICT (service_id, sub_service_code) DO UPDATE SET
    sub_service_name = EXCLUDED.sub_service_name,
    sub_service_description = EXCLUDED.sub_service_description;
