CREATE TABLE IF NOT EXISTS service_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code VARCHAR(50) NOT NULL UNIQUE,
    service_name VARCHAR(100) NOT NULL UNIQUE,
    service_type VARCHAR(50) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO service_types (service_code, service_name, service_type) VALUES
    ('CAR_SERVICE', 'Car Service', 'service'),
    ('BIKE_SERVICE', 'Bike Service', 'service'),
    ('CAR_WASHING', 'Car Washing', 'washing'),
    ('BIKE_WASHING', 'Bike Washing', 'washing')
ON CONFLICT (service_code) DO UPDATE SET
    service_name = EXCLUDED.service_name,
    service_type = EXCLUDED.service_type;
