CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile VARCHAR(15) NOT NULL UNIQUE,
    role_id INTEGER NOT NULL REFERENCES roles(role_id),
    is_mobile_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    is_login_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_profile_updated BOOLEAN NOT NULL DEFAULT FALSE,
    email VARCHAR(255),
    name VARCHAR(150),
    service_center_name VARCHAR(255),
    address_line_1 VARCHAR(255),
    address_line_2 VARCHAR(255),
    city VARCHAR(100),
    pincode VARCHAR(6),
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pincode_format_check CHECK (pincode IS NULL OR pincode ~ '^[0-9]{6}$'),
    CONSTRAINT users_latitude_check CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT users_longitude_check CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'user_id') THEN
        ALTER TABLE users RENAME COLUMN id TO user_id;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS users_user_id_key ON users (user_id);
DO $$ BEGIN
    IF (SELECT column_default IS NULL FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'user_id') THEN
        CREATE SEQUENCE IF NOT EXISTS users_user_id_seq OWNED BY users.user_id;
        PERFORM setval('users_user_id_seq', COALESCE(MAX(user_id), 1), COUNT(*) > 0) FROM users;
        ALTER TABLE users ALTER COLUMN user_id SET DEFAULT nextval('users_user_id_seq');
    END IF;
END $$;

ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_login_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_profile_updated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(150);
ALTER TABLE users ADD COLUMN IF NOT EXISTS service_center_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_line_1 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_line_2 VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pincode VARCHAR(6);
ALTER TABLE users ADD COLUMN IF NOT EXISTS latitude NUMERIC(10, 7);
ALTER TABLE users ADD COLUMN IF NOT EXISTS longitude NUMERIC(10, 7);

UPDATE users SET role_id = 1 WHERE role_id IS NULL;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_id_fkey;
ALTER TABLE users ALTER COLUMN role_id TYPE INTEGER USING role_id::INTEGER;
ALTER TABLE users ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_mobile_role_id_key;
DROP INDEX IF EXISTS users_mobile_role_id_key;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM users GROUP BY mobile HAVING COUNT(*) > 1) THEN
        RAISE EXCEPTION 'Cannot make users.mobile unique: duplicate mobile numbers exist';
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS users_mobile_key ON users (mobile);

DO $$ BEGIN
    ALTER TABLE users ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(role_id);
END $$;
